### ISSUE TITLE
Test gitmagic bot

### ISSUE THREAD

**Issue by gabeio** [gabeio/lissome#179]
reproduction steps:
- do nothing
- do nothing
- do nothing

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue description must include reproduction steps [(?)](https://gitmagic.io/rules/#/issue/body-must-include-reproduction-steps)
- Issue title must start with uppercase [(?)](https://gitmagic.io/rules/#/issue/subject-must-start-with-case)
- Issue title must be in imperative, present tense (e.g. "add", "fix", "change") [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)
- Issue title must be longer than 4 characters [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-longer-than)

[Click here](https://app.gitmagic.io/gabeio/lissome/179/fb9be3e8-b778-4081-9b4b-212397d34408/cf0831e0-2847-4b8b-96c1-47aeb1e009ba) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by ghost** [comment]
This issue still violates some of our guidelines:
- Issue description must include reproduction steps [(?)](https://gitmagic.io/rules/#/issue/body-must-include-reproduction-steps)
- Issue title must be in imperative, present tense (e.g. "add", "fix", "change") [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/gabeio/lissome/179/fb9be3e8-b778-4081-9b4b-212397d34408/cf0831e0-2847-4b8b-96c1-47aeb1e009ba) for details.

**Comment by ghost** [comment]
This issue still violates some of our guidelines:
- Issue description must include reproduction steps [(?)](https://gitmagic.io/rules/#/issue/body-must-include-reproduction-steps)

[Click here](https://app.gitmagic.io/gabeio/lissome/179/fb9be3e8-b778-4081-9b4b-212397d34408/cf0831e0-2847-4b8b-96c1-47aeb1e009ba) for details.

**Comment by ghost** [comment]
Thank you, everything looks good now! :bowtie:
